# Generated by Django 3.0.4 on 2020-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='goal_calories',
            field=models.IntegerField(null=True),
        ),
    ]
