# Generated by Django 3.0.4 on 2020-04-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0003_auto_20200414_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessgoal',
            name='goal',
            field=models.CharField(choices=[('Maintain', 'Maintain'), ('Gain', 'Gain'), ('Lose', 'Lose')], max_length=10),
        ),
    ]
