# Generated by Django 3.0.4 on 2020-05-04 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calcalc', '0009_auto_20200504_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excersice_username_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
