# Generated by Django 3.0.4 on 2020-05-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0010_exercise_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='added_by',
        ),
    ]
