# Generated by Django 3.0.4 on 2020-05-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0016_auto_20200504_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duaration',
            field=models.CharField(choices=[('0 to 30 mins', '0 to 30 mins'), ('30 mins to 1 hour', '30 mins to 1 hour'), ('1 hour to 1 hour and 30 mins', '1 hour to 1 hour and 30 mins')], max_length=100),
        ),
    ]
