# Generated by Django 3.0.4 on 2020-04-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_contents',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_contents',
            field=models.ManyToManyField(to='nutrition.Food'),
        ),
    ]
