# Generated by Django 3.0.4 on 2020-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_remove_meal_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='serving_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_contents',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_contents',
            field=models.ManyToManyField(to='nutrition.Food'),
        ),
    ]
