# Generated by Django 3.0.4 on 2020-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_auto_20200424_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_contents',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_contents',
            field=models.ManyToManyField(to='nutrition.Food'),
        ),
    ]
