# Generated by Django 3.0.4 on 2020-04-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0015_auto_20200424_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='serving_size',
        ),
        migrations.AddField(
            model_name='meal',
            name='Fett_serving_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='KH_serving_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='Protein_serving_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
