# Generated by Django 3.0.4 on 2020-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0016_auto_20200425_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='Fett_serving_size',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='KH_serving_size',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='Protein_serving_size',
        ),
        migrations.AddField(
            model_name='meal',
            name='serving_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
