# Generated by Django 3.0.4 on 2020-04-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0024_meal_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='timestamp',
        ),
    ]
