# Generated by Django 3.0.4 on 2020-05-02 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0027_auto_20200501_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 2, 18, 57, 6, 60663, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
