# Generated by Django 3.0.4 on 2020-05-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0028_meal_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='created',
            new_name='created_at',
        ),
    ]
