# Generated by Django 3.0.4 on 2020-04-23 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lebensmittel', models.CharField(max_length=100)),
                ('KH', models.FloatField(blank=True, null=True)),
                ('Fett', models.FloatField(blank=True, null=True)),
                ('Protein', models.FloatField(blank=True, null=True)),
                ('Calories', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=100, null=True)),
                ('meal_contents', models.CharField(max_length=100, null=True)),
                ('overall_KH', models.FloatField(blank=True, null=True)),
                ('overall_Protein', models.FloatField(blank=True, null=True)),
                ('overall_Fett', models.FloatField(blank=True, null=True)),
                ('overall_Calories', models.IntegerField(blank=True, null=True)),
                ('serving_size', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
