# Generated by Django 3.0.4 on 2020-04-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20200423_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='serving_size',
        ),
    ]
