# Generated by Django 3.0.4 on 2020-04-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_meal_serving_size'),
    ]

    operations = [
    ]
