# Generated by Django 3.0.4 on 2020-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_remove_meal_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='serving_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
