# Generated by Django 3.0.4 on 2020-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_meal_serving_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
