# Generated by Django 3.0.4 on 2020-04-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0017_auto_20200425_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='serving_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
