# Generated by Django 3.0.4 on 2020-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0026_auto_20200501_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='overall_Calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='overall_Fett',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='overall_KH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='overall_Protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
