# Generated by Django 3.0.4 on 2020-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0005_fitnessgoal_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgoal',
            name='optiaml_carbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='optiaml_fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='optiaml_proteins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
