# Generated by Django 3.0.4 on 2020-05-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calcalc', '0006_auto_20200430_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Circuit', 'Circuit')], max_length=10)),
                ('duaration', models.CharField(choices=[('0 to 30 mins', '0 to 30 mins'), ('30 mins to 1 hour', '30 mins to 1 hour'), ('1 hour to 1 hour and 30 mins', '1 hour to 1 hour and 30 mins')], max_length=100)),
                ('calories_burnt', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
