# Generated by Django 3.0.4 on 2020-05-04 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calcalc', '0011_remove_exercise_added_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Workout',
        ),
    ]
