# Generated by Django 3.0.4 on 2020-05-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0014_auto_20200504_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='excercise',
            new_name='workout',
        ),
    ]
