# Generated by Django 3.0.4 on 2020-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcalc', '0018_workout_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Circuit', 'Circuit'), ('Yoga', 'Yoga')], max_length=10),
        ),
    ]
